//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalDataManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int Id { get; set; }
        public int ActionTypeId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Payload { get; set; }
        public int TokenId { get; set; }
        public string DeviceId { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Token Token { get; set; }
        public virtual Device Device { get; set; }
    }
}
