//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalDataManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceUsesToken
    {
        public int Id { get; set; }
        public bool ReadOnly { get; set; }
        public int TokenId { get; set; }
        public string DeviceId { get; set; }
    
        public virtual Token Token { get; set; }
        public virtual Device Device { get; set; }
    }
}
