//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalDataManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DosageContainsSubstances
    {
        public int Id { get; set; }
        public int DosageId { get; set; }
        public int SubstanceId { get; set; }
    
        public virtual Dosage Dosage { get; set; }
        public virtual Substance Substance { get; set; }
    }
}
